[package]
name = "paint-behaviour"
version = "0.1.0"
edition = "2024"

[dependencies]
paint-core.path = "../paint-core"

futures-lite.workspace = true
glam.workspace = true
rayon.workspace = true
tracing.workspace = true
