[language-server.rust-analyzer.config.cargo]
target = "aarch64-linux-android"

[language-server.wgsl-analyzer]
command = "wgsl-analyzer"

[[language]]
name = "wgsl"
scope = "source.wgsl"
file-types = ["wgsl"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = [ "wgsl-analyzer" ]
indent = { tab-width = 4, unit = "    " }
